/* popup pie chart labels and custom themes
   Copyright 2015 Esri
   Licensed under the Apache License, Version 2.0 (http://www.apache.org/licenses/LICENSE-2.0)
*/
define(["require"],function(j){j("dojo/_base/lang dojo/dom-construct esri/core/lang esri/core/requireUtils esri/widgets/Popup/PopupRenderer esri/widgets/Popup/PopupRendererViewModel".split(" "),function(q,i,h,s,r,t){r.prototype._createMediaType=function(a){var b=a.value,c;if("image"===a.type){var f=i.create("img",{alt:a.title||"",src:b.sourceURL});b.linkURL?(c=i.create("a",{title:a.title||"",href:b.linkURL,target:this._preventNewTab(b.linkURL)?"":"_blank"}),i.place(f,c)):c=f}else if(-1!==a.type.indexOf("chart")){c=
i.create("div",{className:"esri-chart"},c);var b=["dojox/charting/Chart2D","dojox/charting/action2d/Tooltip"],d=a.value.theme||this.chartTheme;"string"===typeof d&&(d=d.replace(/\./gi,"/"),-1===d.indexOf("/")&&(d="dojox/charting/themes/"+d));d||(d="dojox/charting/themes/Claro");"string"===typeof d&&b.push(d);this._cancelChartModules();this._chartsPromise=s.when(j,b).then(function(g){this._showChart(c,a.type,a.value,a.showLabels,g[0],g[1],g[2]||d);this._chartsPromise=null}.bind(this))}return c};r.prototype._showChart=
function(a,b,c,f,d,g,h){a=new d(a,{margins:{l:4,t:4,r:4,b:4}});h&&a.setTheme(h);switch(b){case "pie-chart":a.addPlot("default",{type:"Pie",labels:f});a.addSeries("Series A",c.fields);break;case "line-chart":a.addPlot("default",{type:"Markers"});a.addAxis("x",{min:0,majorTicks:!1,minorTicks:!1,majorLabels:!1,minorLabels:!1});a.addAxis("y",{includeZero:!0,vertical:!0,fixUpper:"minor"});c.fields.forEach(function(a,d){a.x=d+1});a.addSeries("Series A",c.fields);break;case "column-chart":a.addPlot("default",
{type:"Columns",gap:3});a.addAxis("y",{includeZero:!0,vertical:!0,fixUpper:"minor"});a.addSeries("Series A",c.fields);break;case "bar-chart":a.addPlot("default",{type:"Bars",gap:3}),a.addAxis("x",{includeZero:!0,fixUpper:"minor",minorLabels:!1}),a.addAxis("y",{vertical:!0,majorTicks:!1,minorTicks:!1,majorLabels:!1,minorLabels:!1}),a.addSeries("Series A",c.fields)}b=new g(a);a.render();this._charts.push(a);this._chartTooltips.push(b)};t.prototype._compileMedia=function(a,b){var c=q.clone(b),f=c.mediaInfos,
d=a.attributes,g=a.layer,i=this.formattedAttributes.global,k=a.substOptions,p,l;f&&(p=[],f.forEach(function(c){l=0;var e=c.value;switch(c.type){case "image":var b=e.sourceURL,b=b&&this._trimString(h.substitute(d,this._fixTokens(b,g)));l=!!b;break;case "pie-chart":case "line-chart":case "column-chart":case "bar-chart":var f,b=e.normalizeField;e.fields=e.fields.map(function(a){return(f=this._getLayerFieldInfo(g,a))?f.name:a},this);b&&(f=this._getLayerFieldInfo(g,b),e.normalizeField=f?f.name:b);l=e.fields.some(function(a){return h.isDefined(d[a])||
-1!==a.indexOf("relationships/")&&this._relatedInfo},this);break;default:return}if(l){var c=q.clone(c),e=c.value,b=c.title?this._processFieldsInLinks(this._fixTokens(c.title,g),d):"",j=c.caption?this._processFieldsInLinks(this._fixTokens(c.caption,g),d):"";c.title=b?this._trimString(h.substitute(i,b,k)):"";c.caption=j?this._trimString(h.substitute(i,j,k)):"";if("image"===c.type)e.sourceURL=h.substitute(d,this._fixTokens(e.sourceURL,g)),e.linkURL&&(e.linkURL=this._trimString(h.substitute(d,this._fixTokens(e.linkURL,
g))));else{var m,n=(b=a.template)&&b.fieldInfos;e.fields.forEach(function(a,c){if(-1!==a.indexOf("relationships/")){var b=this._getRelatedChartInfos(g,n,a,e,d,k);Array.isArray(b)?e.fields=b:e.fields[c]=b}else{b=d[a];b=void 0===b?null:b;m=d[e.normalizeField]||0;b&&m&&(b/=m);var f=n&&this._getFieldInfo(n,a);e.fields[c]={y:b,tooltip:(f&&f.label||a)+": "+this._formatValue(n,b,a,k,!!m)}}},this);c.useTooltipAsLabel&&e.fields.forEach(function(a,b){e.fields[b].text=e.fields[b].tooltip},this)}p.push(c)}},
this));c.mediaInfos=p;return c}})});
