/*

   popup pie chart labels and custom themes for JSAPI 4.1
   Copyright 2015 Esri
   Licensed under the Apache License, Version 2.0 (http://www.apache.org/licenses/LICENSE-2.0)
*/
define(["require"],function(j){j("dojo/_base/lang dojo/dom-construct esri/core/lang esri/core/requireUtils esri/widgets/Popup/PopupRenderer esri/widgets/Popup/PopupRendererViewModel".split(" "),function(q,i,h,s,r,t){r.prototype._createMediaType=function(a){var c=a.value,b;if("image"===a.type){var f=i.create("img",{alt:a.title||"",src:c.sourceURL});c.linkURL?(b=i.create("a",{title:a.title||"",href:c.linkURL,target:this._preventNewTab(c.linkURL)?"":"_blank"}),i.place(f,b)):b=f}else if(-1!==a.type.indexOf("chart")){b=
i.create("div",{className:"esri-popup-renderer__media-chart"},b);var c=["dojox/charting/Chart2D","dojox/charting/action2d/Tooltip"],d=a.value.theme||this.chartTheme;"string"===typeof d&&(d=d.replace(/\./gi,"/"),-1===d.indexOf("/")&&(d="dojox/charting/themes/"+d));d||(d="dojox/charting/themes/Claro");"string"===typeof d&&c.push(d);this._cancelChartModules();this._chartsPromise=s.when(j,c).then(function(c){this._showChart(b,a.type,a.value,a.chartOptions,c[0],c[1],c[2]||d);this._chartsPromise=null}.bind(this))}return b};
r.prototype._showChart=function(a,c,b,f,d,g,h){a=new d(a,{margins:{l:4,t:4,r:4,b:4}});h&&a.setTheme(h);switch(c){case "pie-chart":c={type:"Pie",labels:!1};f&&("boolean"===typeof f.showLabels&&(c.labels=f.showLabels),"number"===typeof f.labelOffset&&(c.labelOffset=f.labelOffset));a.addPlot("default",c);a.addSeries("Series A",b.fields);break;case "line-chart":a.addPlot("default",{type:"Markers"});a.addAxis("x",{min:0,majorTicks:!1,minorTicks:!1,majorLabels:!1,minorLabels:!1});a.addAxis("y",{includeZero:!0,
vertical:!0,fixUpper:"minor"});b.fields.forEach(function(a,d){a.x=d+1});a.addSeries("Series A",b.fields);break;case "column-chart":a.addPlot("default",{type:"Columns",gap:3});a.addAxis("y",{includeZero:!0,vertical:!0,fixUpper:"minor"});a.addSeries("Series A",b.fields);break;case "bar-chart":a.addPlot("default",{type:"Bars",gap:3}),a.addAxis("x",{includeZero:!0,fixUpper:"minor",minorLabels:!1}),a.addAxis("y",{vertical:!0,majorTicks:!1,minorTicks:!1,majorLabels:!1,minorLabels:!1}),a.addSeries("Series A",
b.fields)}b=new g(a);a.render();this._charts.push(a);this._chartTooltips.push(b)};t.prototype._compileMedia=function(a,c){var b=q.clone(c),f=b.mediaInfos,d=a.attributes,g=a.layer,i=this.formattedAttributes.global,k=a.substOptions,p,l;f&&(p=[],f.forEach(function(c){l=0;var e=c.value;switch(c.type){case "image":var b=e.sourceURL,b=b&&this._trimString(h.substitute(d,this._fixTokens(b,g)));l=!!b;break;case "pie-chart":case "line-chart":case "column-chart":case "bar-chart":var f,b=e.normalizeField;e.fields=
e.fields.map(function(a){return(f=this._getLayerFieldInfo(g,a))?f.name:a},this);b&&(f=this._getLayerFieldInfo(g,b),e.normalizeField=f?f.name:b);l=e.fields.some(function(a){return h.isDefined(d[a])||-1!==a.indexOf("relationships/")&&this._relatedInfo},this);break;default:return}if(l){var c=q.clone(c),e=c.value,b=c.title?this._processFieldsInLinks(this._fixTokens(c.title,g),d):"",j=c.caption?this._processFieldsInLinks(this._fixTokens(c.caption,g),d):"";c.title=b?this._trimString(h.substitute(i,b,k)):
"";c.caption=j?this._trimString(h.substitute(i,j,k)):"";if("image"===c.type)e.sourceURL=h.substitute(d,this._fixTokens(e.sourceURL,g)),e.linkURL&&(e.linkURL=this._trimString(h.substitute(d,this._fixTokens(e.linkURL,g))));else{var m,n=(b=a.template)&&b.fieldInfos;e.fields.forEach(function(a,c){if(-1!==a.indexOf("relationships/")){var b=this._getRelatedChartInfos(g,n,a,e,d,k);Array.isArray(b)?e.fields=b:e.fields[c]=b}else{b=d[a];b=void 0===b?null:b;m=d[e.normalizeField]||0;b&&m&&(b/=m);var f=n&&this._getFieldInfo(n,
a);e.fields[c]={y:b,tooltip:(f&&f.label||a)+": "+this._formatValue(n,b,a,k,!!m)}}},this);c.chartOptions&&c.chartOptions.useTooltipAsLabel&&e.fields.forEach(function(a,b){e.fields[b].text=e.fields[b].tooltip},this)}p.push(c)}},this));b.mediaInfos=p;return b}})});
