/*

   popup pie chart labels and custom themes for JSAPI 4.4
   Copyright 2015 Esri
   Licensed under the Apache License, Version 2.0 (http://www.apache.org/licenses/LICENSE-2.0)
*/
define(["require"],function(n){n("dojo/_base/lang dojo/dom-construct esri/core/lang esri/core/requireUtils esri/widgets/Popup/PopupRenderer esri/widgets/Popup/PopupRendererViewModel esri/widgets/support/widget".split(" "),function(t,y,m,v,l,w,z){var u,x=l.prototype._renderMediaInfoType;l.prototype._renderMediaInfoType=function(c,b){u=c;return x.call(this,c,b)};l.prototype._getChartDependencies=function(c){var b=this,a=c["data-media-info"],d=c["data-content-element-index"],f=a.value,h=f.theme||"Claro",
k=a.type;a=["dojox/charting/Chart2D","dojox/charting/action2d/Tooltip"];var g=h;"string"===typeof h&&(g=h.replace(/\./g,"/"),-1===g.indexOf("/")&&(g="dojox/charting/themes/"+g),a.push(g));this._cancelChartModules();this._chartRequirePromise=v.when(n,a).then(function(a){b._renderChart(c,d,k,f,u.chartOptions,a[0],a[1],a[2]||h);clearTimeout(b._chartResizeTimer);b._chartResizeTimer=setTimeout(function(){return b.resize()},0);b._chartRequirePromise=null})};l.prototype._renderChart=function(c,b,a,d,f,h,
k,g){c=new h(c,{margins:{l:4,t:4,r:4,b:4}});g&&c.setTheme(g);switch(a){case "pie-chart":a={type:"Pie",labels:!1};f&&("boolean"===typeof f.showLabels&&(a.labels=f.showLabels),"number"===typeof f.labelOffset&&(a.labelOffset=f.labelOffset));c.addPlot("default",a);c.addSeries("Series A",d.fields);break;case "line-chart":c.addPlot("default",{type:"Markers"});c.addAxis("x",{min:0,majorTicks:!1,minorTicks:!1,majorLabels:!1,minorLabels:!1});c.addAxis("y",{includeZero:!0,vertical:!0,fixUpper:"minor"});d.fields.forEach(function(c,
d){c.x=d+1});c.addSeries("Series A",d.fields);break;case "column-chart":c.addPlot("default",{type:"Columns",gap:3});c.addAxis("y",{includeZero:!0,vertical:!0,fixUpper:"minor"});c.addSeries("Series A",d.fields);break;case "bar-chart":c.addPlot("default",{type:"Bars",gap:3}),c.addAxis("x",{includeZero:!0,fixUpper:"minor",minorLabels:!1}),c.addAxis("y",{vertical:!0,majorTicks:!1,minorTicks:!1,majorLabels:!1,minorLabels:!1}),c.addSeries("Series A",d.fields)}d=new k(c);c.render();this._chartMap.set(b,
{chart:c,tooltip:d})};w.prototype._compileMedia=function(c,b){b=t.clone(b);var a=b.mediaInfos,d=c.attributes,f=c.layer,h=this.formattedAttributes.global,k=c.substOptions,g;if(a){var l=[];a.forEach(function(a){g=0;var e=a.value;switch(a.type){case "image":var b=e.sourceURL;b=b&&this._trimString(m.substitute(d,this._fixTokens(b,f)));g=!!b;break;case "pie-chart":case "line-chart":case "column-chart":case "bar-chart":b=e.normalizeField;e.fields=e.fields.map(function(a){return(p=this._getLayerFieldInfo(f,
a))?p.name:a},this);if(b){var p=this._getLayerFieldInfo(f,b);e.normalizeField=p?p.name:b}g=e.fields.some(function(a){return m.isDefined(d[a])||-1!==a.indexOf("relationships/")&&this._relatedInfo},this);break;default:return}if(g){a=t.clone(a);e=a.value;b=a.title?this._processFieldsInLinks(this._fixTokens(a.title,f),d):"";var n=a.caption?this._processFieldsInLinks(this._fixTokens(a.caption,f),d):"";a.title=b?this._trimString(m.substitute(h,b,k)):"";a.caption=n?this._trimString(m.substitute(h,n,k)):
"";if("image"===a.type)e.sourceURL=m.substitute(d,this._fixTokens(e.sourceURL,f)),e.linkURL&&(e.linkURL=this._trimString(m.substitute(d,this._fixTokens(e.linkURL,f))));else{var q,r=(b=c.template)&&b.fieldInfos;e.fields.forEach(function(a,c){if(-1!==a.indexOf("relationships/"))a=this._getRelatedChartInfos(f,r,a,e,d,k),Array.isArray(a)?e.fields=a:e.fields[c]=a;else{var b=d[a];b=void 0===b?null:b;q=d[e.normalizeField]||0;b&&q&&(b/=q);var g=r&&this._getFieldInfo(r,a);e.fields[c]={y:b,tooltip:(g&&g.label||
a)+":"+this._formatValue(b,{fieldInfos:r,fieldName:a,layer:f,substOptions:k,preventPlacesFormatting:!!q})}}},this);a.chartOptions&&a.chartOptions.useTooltipAsLabel&&e.fields.forEach(function(a,b){e.fields[b].text=e.fields[b].tooltip},this)}l.push(a)}},this)}b.mediaInfos=l;return b}})});
